/* wickra-genome C ABI — generated by cbindgen; do not edit by hand. */

#ifndef WICKRA_GENOME_H
#define WICKRA_GENOME_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A required pointer argument (`handle` or `cmd_json`) was null.
#define WICKRA_GENOME_ERR_NULL -1

// `cmd_json` was not valid UTF-8.
#define WICKRA_GENOME_ERR_UTF8 -2

// A panic was caught at the FFI boundary.
#define WICKRA_GENOME_ERR_PANIC -3

// An opaque handle to a genome instance. Created by [`wickra_genome_new`] and
// destroyed by [`wickra_genome_free`]; never dereferenced by the caller.
//
// The handle caches the most recent command's response in `pending` so the
// two-call length protocol does not run the (potentially expensive) query
// twice. The cache is keyed on the raw command bytes and cleared once the
// response has been delivered.
typedef struct WickraGenome WickraGenome;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Construct a genome handle from a spec JSON. Returns null on a null /
// non-UTF-8 / invalid spec (the spec must carry a non-empty `features` and
// `symbols`). Free it with [`wickra_genome_free`].
//
// # Safety
// `spec_json` must be null or a valid NUL-terminated C string.
WickraGenome *wickra_genome_new(const char *spec_json);

// Destroy a genome handle. Null is a no-op.
//
// # Safety
// `handle` must be null or a handle previously returned by
// [`wickra_genome_new`] and not already freed.
void wickra_genome_free(WickraGenome *handle);

// Apply a command JSON and write the response JSON into the caller's buffer.
//
// Returns the response length in bytes (excluding the terminating NUL), or a
// negative error code. When `len < cap`, the response and a trailing NUL have
// been written to `out`; otherwise `out` is left untouched. Pass `out = NULL`,
// `cap = 0` to query the length.
//
// # Safety
// `handle` must be a valid handle; `cmd_json` a valid NUL-terminated C string;
// `out` either null or a writable buffer of at least `cap` bytes.
int32_t wickra_genome_command(WickraGenome *handle, const char *cmd_json, char *out, uintptr_t cap);

// The library version as a static NUL-terminated string (do not free).
const char *wickra_genome_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_GENOME_H */
